# Generated by Django 3.2.25 on 2025-03-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.CharField(default='projects/default.jpg', max_length=255, verbose_name='Путь к изображению')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на проект')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.IntegerField(default=0, verbose_name='Лет опыта')),
                ('projects_count', models.IntegerField(default=0, verbose_name='Количество проектов')),
                ('clients_count', models.IntegerField(default=0, verbose_name='Количество клиентов')),
                ('positive_reviews', models.IntegerField(default=0, verbose_name='Положительных отзывов')),
                ('hours_worked', models.IntegerField(default=0, verbose_name='Часов работы')),
                ('lines_of_code', models.IntegerField(default=0, verbose_name='Строк кода')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('is_positive', models.BooleanField(default=True, verbose_name='Положительный отзыв')),
                ('date', models.DateField(verbose_name='Дата отзыва')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
    ]
